name: Terraform Plan
on: push
env:
  AWS_ACESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACESS_KEY: ${{secrets.AWS_SECRET_ACESS_KEY}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      